apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::985225484386:role/eksctl-capstone-api-nodegroup-ng-NodeInstanceRole-1VMBSG08EJEU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::985225484386:role/CapstoneCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-19T22:57:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1090"
  uid: 0cfaa331-cd7f-4545-816f-6d12cfd5aef9
