apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::730212195611:role/eksctl-capstone-api-nodegroup-ng-NodeInstanceRole-1G5W0VRHRJDQ0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::730212195611:role/CapstoneCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-22T02:19:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1272"
  uid: da0f09f1-b27f-443e-a20e-8ef00868715e
