apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::342559418112:role/eksctl-capstone-api-nodegroup-ng-NodeInstanceRole-1JW8OKMM0AY5N
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::342559418112:role/CapstoneCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-21T19:09:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1645"
  uid: 50bebc9f-9bf0-446e-83c0-f46747e4e014
