apiVersion: v1
kind: Service
metadata:
  name: capstone-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: capstone-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: capstone-api
  template:
    metadata:
      labels:
        app: capstone-api
    spec:
      containers:
        - name: capstone-api
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
          env:
            - name: AUTH0_DOMAIN
              value: AUTH0_DOMAIN_VALUE
            - name: ALGORITHMS
              value: ALGORITHMS_VALUE
            - name: API_AUDIENCE
              value: API_AUDIENCE_VALUE
            - name: AUTH0_CLIENT_ID
              value: AUTH0_CLIENT_ID_VALUE
            - name: AUTH0_CALLBACK_URL
              value: AUTH0_CALLBACK_URL_VALUE
            - name: DB_HOST
              value: DB_HOST_VALUE
            - name: DB_USER
              value: DB_USER_VALUE
            - name: DB_PASSWORD
              value: DB_PASSWORD_VALUE
            - name: DB_NAME
              value: DB_NAME_VALUE
            - name: TOKEN_DEALER
              value: TOKEN_DEALER_VALUE
            - name: TOKEN_DEALER_MANAGER
              value: TOKEN_DEALER_MANAGER_VALUE
